In [ ]:
#corn, apple, grape, tomato and potato
#barley potato maize wheat

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("../data/new/crop.csv")

In [21]:
df

,Soilcolor,Ph,K,P,N,Zn,S,QV2M-W,QV2M-Sp,QV2M-Su,...,PRECTOTCORR-W,PRECTOTCORR-Sp,PRECTOTCORR-Su,PRECTOTCORR-Au,WD10M,GWETTOP,CLOUD_AMT,WS2M_RANGE,PS,label
0,Yellowish brown,5.81,738.231,5.401,0.2300,2.976000,13.816,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
1,Yellowish brown,5.43,606.382,10.478,0.2300,3.077000,16.421,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
2,brown,5.41,386.580,6.847,0.2300,6.611000,16.557,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
3,red,5.65,207.086,3.418,0.2300,0.460181,16.075,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
4,red,5.27,317.357,39.282,0.2300,2.743000,12.558,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3862,black,6.67,378.208,4.490,0.2300,0.514285,14.540,7.650000,7.773333,10.986667,...,1.170000,2.243333,7.520000,2.88,81.06,0.69,53.45,6.48,75.83,Wheat
3863,brown,5.82,231.413,2.997,0.2300,3.039000,13.789,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3864,black,5.75,327.328,12.279,0.2518,2.012000,24.843,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3865,brown,5.47,211.224,3.064,0.2300,3.389000,13.826,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3866,black,5.79,181.998,7.342,0.2300,2.630000,19.640,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat

In [22]:
df = df.rename(columns={
    "Soilcolor": "color",
    "Ph": "ph",
    "K": "k",
    "P": "p",
    "N": "n",
    "Zn": "zn",
    "S": "s",
    "QV2M-W": "hum_w",
    "QV2M-Sp": "hum_sp",
    "QV2M-Su": "hum_su",
    "QV2M-Au": "hum_au",
    "T2M_MAX-W": "tmax_w",
    "T2M_MAX-Sp": "tmax_sp",
    "T2M_MAX-Su": "tmax_su",
    "T2M_MAX-Au": "tmax_au",
    "T2M_MIN-W": "tmin_w",
    "T2M_MIN-Sp": "tmin_sp",
    "T2M_MIN-Su": "tmin_su",
    "T2M_MIN-Au": "tmin_au",
    "PRECTOTCORR-W": "rain_w",
    "PRECTOTCORR-Sp": "rain_sp",
    "PRECTOTCORR-Su": "rain_su",
    "PRECTOTCORR-Au": "rain_au",
    "WD10M": "wind_dir",
    "GWETTOP": "soil_moist",
    "CLOUD_AMT": "cloud",
    "WS2M_RANGE": "wind_rng",
    "PS": "pressure",
    "label": "crop_type"
})
df

,color,ph,k,p,n,zn,s,hum_w,hum_sp,hum_su,...,rain_w,rain_sp,rain_su,rain_au,wind_dir,soil_moist,cloud,wind_rng,pressure,crop_type
0,Yellowish brown,5.81,738.231,5.401,0.2300,2.976000,13.816,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
1,Yellowish brown,5.43,606.382,10.478,0.2300,3.077000,16.421,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
2,brown,5.41,386.580,6.847,0.2300,6.611000,16.557,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
3,red,5.65,207.086,3.418,0.2300,0.460181,16.075,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
4,red,5.27,317.357,39.282,0.2300,2.743000,12.558,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3862,black,6.67,378.208,4.490,0.2300,0.514285,14.540,7.650000,7.773333,10.986667,...,1.170000,2.243333,7.520000,2.88,81.06,0.69,53.45,6.48,75.83,Wheat
3863,brown,5.82,231.413,2.997,0.2300,3.039000,13.789,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3864,black,5.75,327.328,12.279,0.2518,2.012000,24.843,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3865,brown,5.47,211.224,3.064,0.2300,3.389000,13.826,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3866,black,5.79,181.998,7.342,0.2300,2.630000,19.640,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat

In [27]:
df.columns

Index(['color', 'ph', 'k', 'p', 'n', 'zn', 's', 'hum_w', 'hum_sp', 'hum_su',
       'hum_au', 'tmax_w', 'tmax_sp', 'tmax_su', 'tmax_au', 'tmin_w',
       'tmin_sp', 'tmin_su', 'tmin_au', 'rain_w', 'rain_sp', 'rain_su',
       'rain_au', 'wind_dir', 'soil_moist', 'cloud', 'wind_rng', 'pressure',
       'crop_type'],
      dtype='object')

In [24]:
df

,color,ph,k,p,n,zn,s,hum_w,hum_sp,hum_su,...,rain_w,rain_sp,rain_su,rain_au,wind_dir,soil_moist,cloud,wind_rng,pressure,crop_type
0,Yellowish brown,5.81,738.231,5.401,0.2300,2.976000,13.816,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
1,Yellowish brown,5.43,606.382,10.478,0.2300,3.077000,16.421,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
2,brown,5.41,386.580,6.847,0.2300,6.611000,16.557,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
3,red,5.65,207.086,3.418,0.2300,0.460181,16.075,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
4,red,5.27,317.357,39.282,0.2300,2.743000,12.558,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3862,black,6.67,378.208,4.490,0.2300,0.514285,14.540,7.650000,7.773333,10.986667,...,1.170000,2.243333,7.520000,2.88,81.06,0.69,53.45,6.48,75.83,Wheat
3863,brown,5.82,231.413,2.997,0.2300,3.039000,13.789,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3864,black,5.75,327.328,12.279,0.2518,2.012000,24.843,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3865,brown,5.47,211.224,3.064,0.2300,3.389000,13.826,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3866,black,5.79,181.998,7.342,0.2300,2.630000,19.640,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat

Rice, Potato, Tomato, Wheat, Barley, Corn

In [30]:
df['crop_type'].unique()

array(['Barley', 'Bean', 'Dagussa', 'Fallow', 'Maize', 'Niger seed',
       'Pea', 'Potato', 'Red Pepper', 'Sorghum', 'Teff', 'Wheat'],
      dtype=object)

In [42]:
df.isnull().sum()

color         0
ph            0
k             0
p             0
n             0
zn            0
s             0
hum_w         0
hum_sp        0
hum_su        0
hum_au        0
tmax_w        0
tmax_sp       0
tmax_su       0
tmax_au       0
tmin_w        0
tmin_sp       0
tmin_su       0
tmin_au       0
rain_w        0
rain_sp       0
rain_su       0
rain_au       0
wind_dir      0
soil_moist    0
cloud         0
wind_rng      0
pressure      0
crop_type     0
dtype: int64

In [33]:
df = df[~df['crop_type'].isin([ 'Dagussa', 'Fallow', 'Niger seed', 'Red Pepper', 'Sorghum', 'Teff'])]

In [34]:
df['crop_type'].unique()

array(['Barley', 'Bean', 'Maize', 'Pea', 'Potato', 'Wheat'], dtype=object)

In [35]:
df = df.sort_values(by ='crop', ascending=True )

KeyError: 'crop'

In [36]:
df

,color,ph,k,p,n,zn,s,hum_w,hum_sp,hum_su,...,rain_w,rain_sp,rain_su,rain_au,wind_dir,soil_moist,cloud,wind_rng,pressure,crop_type
0,Yellowish brown,5.81,738.231,5.401,0.2300,2.976000,13.816,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
1,Yellowish brown,5.43,606.382,10.478,0.2300,3.077000,16.421,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
2,brown,5.41,386.580,6.847,0.2300,6.611000,16.557,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
3,red,5.65,207.086,3.418,0.2300,0.460181,16.075,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
4,red,5.27,317.357,39.282,0.2300,2.743000,12.558,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3862,black,6.67,378.208,4.490,0.2300,0.514285,14.540,7.650000,7.773333,10.986667,...,1.170000,2.243333,7.520000,2.88,81.06,0.69,53.45,6.48,75.83,Wheat
3863,brown,5.82,231.413,2.997,0.2300,3.039000,13.789,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3864,black,5.75,327.328,12.279,0.2518,2.012000,24.843,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3865,brown,5.47,211.224,3.064,0.2300,3.389000,13.826,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3866,black,5.79,181.998,7.342,0.2300,2.630000,19.640,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat

In [37]:
print(df['crop_type'].value_counts())

crop_type
Maize     732
Wheat     715
Barley    503
Bean      253
Pea        94
Potato     48
Name: count, dtype: int64

In [41]:
df

,color,ph,k,p,n,zn,s,hum_w,hum_sp,hum_su,...,rain_w,rain_sp,rain_su,rain_au,wind_dir,soil_moist,cloud,wind_rng,pressure,crop_type
0,Yellowish brown,5.81,738.231,5.401,0.2300,2.976000,13.816,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
1,Yellowish brown,5.43,606.382,10.478,0.2300,3.077000,16.421,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
2,brown,5.41,386.580,6.847,0.2300,6.611000,16.557,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
3,red,5.65,207.086,3.418,0.2300,0.460181,16.075,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
4,red,5.27,317.357,39.282,0.2300,2.743000,12.558,7.993333,10.456667,11.963333,...,2.073333,5.270000,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3862,black,6.67,378.208,4.490,0.2300,0.514285,14.540,7.650000,7.773333,10.986667,...,1.170000,2.243333,7.520000,2.88,81.06,0.69,53.45,6.48,75.83,Wheat
3863,brown,5.82,231.413,2.997,0.2300,3.039000,13.789,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3864,black,5.75,327.328,12.279,0.2518,2.012000,24.843,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3865,brown,5.47,211.224,3.064,0.2300,3.389000,13.826,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat
3866,black,5.79,181.998,7.342,0.2300,2.630000,19.640,7.183333,7.650000,10.476667,...,2.073333,2.613333,4.836667,3.63,75.69,0.65,0.46,46.10,74.17,Wheat

In [ ]:
# crop_counts = df1['crop'].value_counts()

# for crop, count in crop_counts.items():
#     print(f'{crop}: {count}')

In [38]:
df.to_csv("../data/new/crop_main.csv")

In [39]:
df.isnull().sum()

color         0
ph            0
k             0
p             0
n             0
zn            0
s             0
hum_w         0
hum_sp        0
hum_su        0
hum_au        0
tmax_w        0
tmax_sp       0
tmax_su       0
tmax_au       0
tmin_w        0
tmin_sp       0
tmin_su       0
tmin_au       0
rain_w        0
rain_sp       0
rain_su       0
rain_au       0
wind_dir      0
soil_moist    0
cloud         0
wind_rng      0
pressure      0
crop_type     0
dtype: int64

In [40]:
df.describe()

,ph,k,p,n,zn,s,hum_w,hum_sp,hum_su,hum_au,...,tmin_au,rain_w,rain_sp,rain_su,rain_au,wind_dir,soil_moist,cloud,wind_rng,pressure
count,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,...,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000,2345.000000
mean,5.787731,330.197411,13.250708,0.195187,1.903796,11.894296,8.323417,9.065309,12.153502,10.915069,...,8.522724,1.597592,4.048580,14.243801,4.857952,72.900290,0.710311,49.575569,9.862977,78.165198
std,0.591211,223.458960,39.979200,0.065491,1.448193,5.640072,0.662549,0.869946,0.967484,1.088874,...,2.289171,0.706777,1.148018,4.604731,1.362818,82.882924,0.052563,18.761715,12.135306,2.477829
min,4.400000,41.134000,0.000000,0.000262,0.100000,0.050000,7.183333,7.650000,10.476667,9.070000,...,3.980000,0.000000,1.940000,4.836667,2.156667,0.060000,0.520000,0.460000,4.860000,74.170000
25%,5.400000,181.860000,2.400000,0.160000,1.100000,8.000000,7.933333,8.403333,11.413333,10.150000,...,8.260000,0.910000,2.613333,11.766667,3.630000,36.060000,0.690000,48.620000,5.410000,76.540000
50%,5.730000,280.011000,4.000000,0.203200,1.590000,11.000000,8.383333,9.340000,12.166667,10.926667,...,8.290000,1.736667,4.410000,16.620000,5.430000,68.940000,0.730000,59.110000,6.010000,77.290000
75%,6.070000,415.000000,8.965000,0.230000,2.280000,15.000000,8.910000,9.543333,12.836667,11.433333,...,10.700000,2.073333,5.203333,17.816667,5.823333,81.060000,0.740000,59.110000,6.260000,79.610000
max,8.500000,2119.000000,782.000000,0.695600,27.000000,118.347000,9.723333,10.703333,13.853333,12.800000,...,13.643333,2.780000,5.660000,19.920000,7.420000,354.880000,0.800000,59.110000,46.100000,83.760000